### ISSUE TITLE
Deprecated login method

### ISSUE THREAD

**Issue by mobilemeans** [flaccid/com.rightscale.api.client#1]
The following error appears in my console when running the current version of the code as a Java project in Eclipse.  "Basic auth is deprecated for calls other than login. Please 'login' to get a session and pass the session back for further actions."

Is there a new method for login?

Thanks

**Comment by flaccid** [comment]
HTTP Basic Auth was deprecated for API calls some years ago (except the login action). Subsequent API calls should send the cookie session back that was returned from initial login.
The other alternate auth method is oauth where the api token retrieved is sent with each API call.
We should add support for both the cookie store and oauth and ensure API 1.5 works ok.
For some basic info see http://docs.rightscale.com/api/api_1.5_examples/authentication.html.

**Comment by githubvick** [comment]
Hi flaccid,

We are already setting the cookie value we obtained during login from these lines

builder.cookie(cookies.get(0));
builder.header("X-API-VERSION", apiVersion);
response = builder.get(ClientResponse.class);

What is it extra that we need to do? If you could provide the details, maybe I can try it out.

Thanks.

**Comment by flaccid** [comment]
Thanks for your patience @mobilemeans @githubvick. I had not realized that API 1.5 was not implemented yet, 2 years ago it was pretty early. I have fixed it up for you, should be pretty clear. We can ignore 1.0, just use 1.5 now; raise a new issue if any problems, cheers! p.s. both cookies need to be passed which was likely your issue there @githubvick.
